### ISSUE TITLE
How to use the library

### ISSUE THREAD

**Issue by ta3pks** [jayjamesjay/http_req#2]
I have no clue how to do a get request with headers, I have tried the request builder which after calling send just hangs nothing happens.

**Comment by jayjamesjay** [comment]
This might be caused by default configuration of `RequestBuilder` in newest version of the crate. By default it doesn't include header `Connection: Close` in request message. This means that connection will not be closed after completion of the response.

Please try adding header `Connection: Close` by using `header` method on created `RequestBuilder`. (`builder.header("Connection", "Close")`).

Please also check out [full example](https://gist.github.com/jayjamesjay/8ae9e4243aaa12fbc236058517a39c06).

**Comment by ta3pks** [comment]
@jayjamesjay also i am really confused why do we have to pass a TCP connection isn't the entire idea of a HTTP client to do things autonomously

**Comment by jayjamesjay** [comment]
@NikosEfthias I think I understand you point. This approach may seem strange. My intention is to give user of the library option to use any `struct` which implements `Read` and `Write` as a stream. They might use `TcpStream` from `std`, define their own `struct`, etc.

I realized that I should have mentioned all those things in the documentation.
I'm going to provide implementation of methods `header` and `headers` for `Request` (which automatically creates `TcpStream`/`TlsStream`) with the next version of the crate.

**Comment by brycefisher** [comment]
@jayjamesjay would you accept a PR which adds a convenience method to construct the underlying TcpStream?

**Comment by jayjamesjay** [comment]
@brycefisher Please explain me your idea in more details. I didn't add any special function to help in creating a TcpStream for RequestBuilder, because I hadn't thought that it might be useful - in the current version of crate request can be created using `Request` with default TcpStream or `RequestBuilder` and then make use of any TcpStream (struct with implemented `Write` and `Read`). In both cases you can modify request parameters (headers, request method, body) with the nearly the same functions (except for http `version`, which I haven't added yet).

**Comment by brycefisher** [comment]
@jayjamesjay -- ah! I misunderstood the API. I see now what you mean and that my offer doesn't really make sense.
