### ISSUE TITLE
Steam issue or how can i send special Request-Headers?

### ISSUE THREAD

**Issue by cyberpunkbln** [jayjamesjay/http_req#20]
Hello,
i have a little problem, for that code:

```
let steamUrl: Uri = "https://store.steampowered.com/api/appdetails/?appids=794270&filters=basic&l=de".parse().unwrap();
let mut writer = Vec::new();
let res = request::get(steamUrl.to_string(), &mut writer).unwrap();
```

He don't respect the &l=de parameter and send all response content in english. The filters parameter he accept fine. I think it is the Request-Header that i must tweak. I think i must send Accept-Language like Firefox. How can i made this?

thx

**Comment by jayjamesjay** [comment]
You're right, you need to add header "Accept-Language: de" to request. Even though "l=de" parameter is included in request, server does not respect it.

In order to add a header to request, you have to replace `get` function from `request` module with `Request` struct from the same module. You create it with method `new`. Then you can add or modify parameters of the request. You can add header by using its method `header`. Finally you may send the request by calling `send`. 
```rust
use http_req::{request::Request, uri::Uri};

let steamUrl: Uri = "https://store.steampowered.com/api/appdetails/?appids=794270&filters=basic&l=de".parse().unwrap();

let mut writer = Vec::new();
let res = Request::new(&steamUrl).header("Accept-Language", "de").send(&mut writer).unwrap();
```
Plese check out the docs for more information: [http_req::request::Request](https://docs.rs/http_req/0.5.0/http_req/request/struct.Request.html)

**Comment by cyberpunkbln** [comment]
@jayjamesjay Perfectly, thx.
