### ISSUE TITLE
Failed sending request with "https://bing.com"

### ISSUE THREAD

**Issue by ghost** [jayjamesjay/http_req#5]
Hello developers,

In version `0.4.4`, this code fails:

```rust
use std::io;
use http_req::request::Request;
fn main() {
    let uri = &"https://bing.com".parse().unwrap();
    if let Err(err) = Request::new(&uri).send(&mut io::sink()) {
        eprintln!("{:?}", err);
    }
}
```

The message printed is: `Parse(Invalid)`.

If the url is changed to `"https://www.bing.com"`, it works fine.

May I ask if you could fix?

Thank you,

---
### _Edited_

`"https://bing.com"` returns `301`, while `"https://www.bing.com"` returns `200`. Maybe it was the cause?

**Comment by jayjamesjay** [comment]
The issue occurs during parsing the server's response. It is caused by lack of Reason-Phrase in first line (Status line) of response. I haven't predicted that there might be no Reason-Phrase in Status line which is why library treats it as invalid.

I'm going to release a fix in a few hours.

Thank you for posting the issue.
