### ISSUE TITLE
Set body of `Request`

### ISSUE THREAD

**Issue by colelawrence** [jayjamesjay/http_req#9]
Hello, would it make sense to be able to set the `RequestBuilder`'s body via a `Request`?
Currently, I only see the ability to send a body when using the `RequestBuilder`.

Perhaps even the ability to implement `From<RequestBuilder> for Request` would be nice.

Cheers,

Cole

**Comment by jayjamesjay** [comment]
To my mind, being able to set the `RequestBuilder`'s body via a `Request` seems to be very useful. 
Implementing `From<RequestBuilder> for Request` is not a bad idea but I'm not sure if it won't be a bit confusing, because `RequestBuilder` can use any TcpStream/TlsStream while `Request` uses predefined ones.

Thanks for contribution. If you can, please add some tests.
I am going to release this upade with the next version of crate.
